config/routes.rb
Goals::Application.routes.draw do
  devise_for :users
  resources :goals do
    resources :goal_entries
    member do
      post :archive
    end
    collection do
      get :archived
    end
  end
  namespace :api do
    namespace :v1 do
      resources :goals do
        resources :goal_entries
      end
      resources :goal_entries
    end
  end
  root :to => 'static#index'
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  attr_accessible :name, :user_id
  
  has_many :goal_entries, :order => "occured_on", dependent: :destroy
  
  def longest_chain
    return goal_entries.count if [1,0].include?( goal_entries.count )
    cur_chain = 1
    max_chain = 0
    #Loop through the goals incrementing chains
    1.upto( goal_entries.count-1).each do |i|
      if  goal_entries[i].occured_on - 1 == goal_entries[i-1].occured_on
         cur_chain += 1
      else
        max_chain = cur_chain if cur_chain > max_chain
        cur_chain = 1
      end
    end
     max_chain = cur_chain if cur_chain > max_chain
    return max_chain
  end
  
  def entries_on_date?( date )
    !!goal_entries.group( :occured_on ).count()[ date ]
  end
  
  def archive!
    self.archived = true
    self.save
  end
  
end

app/models/goal_entry.rb
class GoalEntry < ActiveRecord::Base
  attr_accessible :goal_id, :occured_on
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :goals
  has_many :goal_entries, through: :goals
  def unarchived_goals
    self.goals.where( archived: false )
  end
  
  def archived_goals
    self.goals.where( archived: true )
  end
  
  def unarchived_goal_entries
    self.goal_entries.where( goals: { archived: false })
  end
  
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  
  respond_to :json
  
end

app/controllers/api/v1/goal_entries_controller.rb
class Api::V1::GoalEntriesController < Api::V1::BaseController
  
  skip_before_filter  :verify_authenticity_token
  
  def index
    respond_with current_user.unarchived_goal_entries
  end
  
  def show
    respond_with current_user.goal_entries.find( params[:goal_id] )
  end
  
  def create
    puts current_user.inspect
    goal = current_user.goals.find( params[:goal_id] )
    goal_entry = goal.goal_entries.create( occured_on: params[:occured_on])
    respond_with :api,:v1, goal_entry
  end
  
  def destroy
    ge = current_user.goal_entries.find( params[:id] )
    respond_with ge.destroy
  end
  
end

app/controllers/api/v1/goals_controller.rb
class Api::V1::GoalsController < Api::V1::BaseController
  
  def index
    respond_with current_user.unarchived_goals
  end
  
  def update
    @goal = Goal.find(params[:id])
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/goal_entries_controller.rb
class GoalEntriesController < ApplicationController
  
  before_filter :authenticate_user!
  
  def update
    @goal = current_user.goals.find(params[:goal_id])
    @goal.goal_entries.find_or_create_by_occured_on( occured_on: params[:id ])
    render nothing: true
  end
  
  def destroy
    @goal = current_user.goals.find(params[:goal_id])
    @ge = @goal.goal_entries.find_by_occured_on( params[:id])
    @ge.destroy
    render nothing: true
  end
  
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  
  before_filter :authenticate_user!

  def index
    @goals = current_user.unarchived_goals.includes(:goal_entries)
  end
  
  def new
    @goal = Goal.new
  end
  
  def edit
    @goal = current_user.unarchived_goals.find params[:id]
  end
  
  def update
    @goal = current_user.unarchived_goals.find params[:id]
    if @goal.update_attributes( params[:goal] )
      redirect_to goals_path
    else
      render action: :new
    end
  end
  
  def create
    @goal = current_user.unarchived_goals.build( params[:goal] )
    if @goal.save
      redirect_to goals_path
    else
      render action: :new
    end
  end
  
  def destroy
    @goal = current_user.unarchived_goals.find params[:id]
    @goal.delete
    redirect_to goals_path
  end
  
  def archive
    @goal = current_user.unarchived_goals.find params[:id]
    @goal.archive!
    redirect_to goals_path
  end
  
  def archived
    @goals = current_user.archived_goals
  end
  
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/goals/archived.html.haml
.container
  .row
    .span12
      %table
        %tr
          %td Goal Name
          %td Checks
          %td Longest Chain
        - for goal in @goals
          %tr
            %td= goal.name
            %td=goal.goal_entries.count
            %td= goal.longest_chain

app/views/goals/edit.html.haml
.container
  .row
    .span6.offset3
      %h2 Edit Goal
      = bootstrap_form_for @goal do |f|
        = f.text_field :name
        = f.submit
      %h2 Delete Goal
      = button_to "Delete", @goal, confirm: "Are you sure?", method: :delete, class: "btn btn-primary"
      = button_to "Archive", archive_goal_path( @goal ), confirm: "Are you sure you want to archive this goal?", method: :post, class: "btn btn-primary"

app/views/goals/index.html.haml
%script{type:"text/javascript"}
  window.token = '<%= form_authenticity_token %>'
.container
  = link_to "Add Goal", new_goal_path
.container#goals
  %table
    %tr
      %th
        %i.icon-arrow-left{"ng-click" => "decreaseDate()"}
      %th{"ng-repeat"=>"date in dates"} {{ pad(date.getMonth()+1,2) }}/{{ pad( date.getDate(),2) }}
      %th
        %i.icon-arrow-right{"ng-click" => "increaseDate()"}
        %i.icon-calendar{"ng-click"=>"showHide=!showHide"}
        .goalsCalendar{"ng-show"=>"showHide", "ui-date"=>'{onSelect:selectDate}', 'ng-model'=>'date'}
    %tr{"ng-repeat"=>"goal in goals"}
      %th {{ goal.name }}
      %td.goal-available{"ng-repeat"=>"date in dates", "ng-bind-html-unsafe" => "goalEntryIconsForDate( goal, date )", "ng-click"=>"goalEntryClick(goal,date)" }
      %td.disappear
        Checks: {{ checkCount( goal ) }}
        %br
        Current Chain: {{ currentChain( goal ) }}
        %br
        Longest Chain: {{ longestChain( goal ) }}
  = link_to "Archived Goals", archived_goals_path

app/views/goals/new.html.haml
.container
  .row
    .span6.offset3
      = bootstrap_form_for @goal, html: { class: "form-horizontal" } do |f|
        = f.text_field :name
        = f.submit "Submit"

app/views/layouts/application.html.haml
!!! 5
%html{"ng-app"=>"goalsapp"}
  %head
    %title Goals
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{name: "viewport", content:"width=device-width, initial-scale=1.0"}
  %body{"ng-controller"=>"GoalsCtrl"}
    %header
      .container
        .pull-right
          - if current_user
            Welcome 
            =link_to current_user.email, edit_user_registration_path
            =link_to "My Goals", goals_path
            =link_to "Log Out", destroy_user_session_path
          - else 
            =link_to "Register", new_user_registration_path
            =link_to "Login", new_user_session_path
    = content_for?(:content) ? yield(:content) : yield

app/views/layouts/devise.html.haml
=content_for :content do
  .container
    .row
      .span12
        =yield

= render template: "layouts/application"